### PR TITLE
throwing the correct error

### LINKED ISSUE #16: compatibility layer exceptions are hidden
The compatibility invocation handler doesn't propagate exceptions properly, any invocation exception thrown will get logged and the original TAppplicationException is thrown which is incorrect.

Example stacktrace in the logs:
```19/01/10 09:43:52 WARN closeable.CloseableMetaStoreClientInvocationHandler: Unable to run compatibility for metastore client method getTable. Will rethrow original exception:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.hotels.hcommon.hive.metastore.client.closeable.CloseableMetaStoreClientInvocationHandler.invokeCompatibility(CloseableMetaStoreClientInvocationHandler.java:66)
	at com.hotels.hcommon.hive.metastore.client.closeable.CloseableMetaStoreClientInvocationHandler.invoke(CloseableMetaStoreClientInvocationHandler.java:53)
	at com.sun.proxy.$Proxy94.getTable(Unknown Source)
	at com.hotels.bdp.circustrain.core.HiveEndpoint.getTable(HiveEndpoint.java:100)
	at com.hotels.bdp.circustrain.core.replica.Replica.validateReplicaTable(Replica.java:291)
	at com.hotels.bdp.circustrain.core.UnpartitionedTableReplication.replicate(UnpartitionedTableReplication.java:84)
	at com.hotels.bdp.circustrain.core.Locomotive.run(Locomotive.java:114)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:781)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at com.hotels.bdp.circustrain.CircusTrain.main(CircusTrain.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:234)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:148)
Caused by: NoSuchObjectException(message:db.table1 table not found)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_table_result$get_table_resultStandardScheme.read(ThriftHiveMetastore.java:53203)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_table_result$get_table_resultStandardScheme.read(ThriftHiveMetastore.java:53171)
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$get_table_result.read(ThriftHiveMetastore.java:53102)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.hotels.hcommon.hive.metastore.compatibility.HiveMetaStoreClientCompatibility12x.receiveBase(HiveMetaStoreClientCompatibility12x.java:89)
	at com.hotels.hcommon.hive.metastore.compatibility.HiveMetaStoreClientCompatibility12x.recv_get_table(HiveMetaStoreClientCompatibility12x.java:135)
	at com.hotels.hcommon.hive.metastore.compatibility.HiveMetaStoreClientCompatibility12x.get_table(HiveMetaStoreClientCompatibility12x.java:113)
	at com.hotels.hcommon.hive.metastore.compatibility.HiveMetaStoreClientCompatibility12x.getTable(HiveMetaStoreClientCompatibility12x.java:103)
```
The cause `NoSuchObjectException` is not thrown but just logged. It should be thrown.

### PR DESCRIPTION
**Pull request by patduin**
fixes #16

### CODE REVIEW

File: src/main/java/com/hotels/hcommon/hive/metastore/client/closeable/CloseableMetaStoreClientInvocationHandler.java [hunk 1]
```diff
@@ -45,18 +42,25 @@
...
-      } catch (Throwable t) {
-        log.warn("Unable to run compatibility for metastore client method {}. Will rethrow original exception: ",
-            method.getName(), t);
+      } catch (InvocationTargetException compatibilityException) {
+        if (compatibilityException.getCause().getClass().isAssignableFrom(TApplicationException.class)) {
+          log
+              .warn("Unable to run compatibility for metastore client method {}. Will rethrow original exception: ",
+                  method.getName(), compatibilityException);
+        } else {
+          // compatibily worked but threw non TApplicaitonException, rethrowing cause.
```
Comment (AnanaMJ) [inline src/main/java/com/hotels/hcommon/hive/metastore/client/closeable/CloseableMetaStoreClientInvocationHandler.java]: `TApplicaitonException` -> `TApplicationException`

**Review by abhimanyugupta07 — APPROVED** [review]

File: CHANGELOG.md [hunk 2]
```diff
@@ -6,6 +6,7 @@
 * Removed transitive (provided) dependency on `hbase-client`.
 ### Fixed
 * Removed 'isOpen()' method from CloseableMetaStoreClient. See [#11](https://github.com/HotelsDotCom/hcommon-hive-metastore/issues/11).
+* Issue where the wrong exception was being propagated in the compatibility layer.
```
Comment (massdosage) [inline CHANGELOG.md]: Could you create a quick GH issue with the relevant part of the stack trace and link it here? Just so in future we have a reference to this with some more detail.

File: src/test/java/com/hotels/hcommon/hive/metastore/client/closeable/CloseableMetaStoreClientInvocationHandlerTest.java [hunk 3]
```diff
@@ -68,22 +71,66 @@ public Object answer(InvocationOnMock invocation) throws Throwable {
...
+  public void rethrowCompatibilityClassException() throws Throwable {
+    Class<?> clazz = Class.forName(IMetaStoreClient.class.getName());
+    Method method = clazz.getMethod("getTable", String.class, String.class);
+    String dbName = "db";
+    String tableName = "table";
+
+    IMetaStoreClient exceptionThrowingClient = Mockito.mock(IMetaStoreClient.class, new Answer<Void>() {
       @Override
-      public Object answer(InvocationOnMock invocation) throws Throwable {
-        throw new RuntimeException();
```
Comment (massdosage) [inline src/test/java/com/hotels/hcommon/hive/metastore/client/closeable/CloseableMetaStoreClientInvocationHandlerTest.java:82]: Shouldn't we still test what happens if something unexpected like a `RuntimeException` is thrown?

Comment (patduin) [reply src/test/java/com/hotels/hcommon/hive/metastore/client/closeable/CloseableMetaStoreClientInvocationHandlerTest.java:82]: Well no this test is fine,because any exception will be wrapped in a `InvocationTargetException`. So I changed this as it is more realistic.

File: CHANGELOG.md (hunk 2 above)
Comment (patduin) [reply CHANGELOG.md]: https://github.com/HotelsDotCom/hcommon-hive-metastore/issues/16

**Review by massdosage — APPROVED** [review]
